/****************************************************************************
**
**This file was generated by the author
**
**Marcelo Teixeira Silveira, E-FOTO 2006
****************************************************************************/

#ifndef IMAGEVIEW_H
#define IMAGEVIEW_H

#include <QPainter>
#include <QImage>
#include <QPixmap>
#include <QPoint>
#include <QString>
#include <QCursor>
#include <QBitmap>
#include <QMessageBox>
#include <QRect>
#include <QPolygon>
#include <QMouseEvent>
#include <QWheelEvent>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsItem>
#include <QStandardItemModel>

#include "SWidgetQt.h"

#include <iostream>
using namespace std;


class ImageView : public SWidgetQt
{
	Q_OBJECT

public:
	ImageView(QWidget* parent = 0);
	ImageView(QString file, QWidget* parent = 0);
	~ImageView();

public slots:
	void setViewMode(int m);
	int getViewMode();
	void fitView();
	void createPoints(QStandardItemModel* points, int mode);
	void drawPoints(QStandardItemModel* points, int mode);
	void clearPoints();
	void drawFlightDirection(int x, int y);
	bool loadImage(QString file);

signals:
	void sendCoord(QPoint);
	void markClicked(QPoint);
	void flightDirectionClicked(QPoint);
	void mousePressed();
	void changed();

protected:
	void mousePressEvent(QMouseEvent* e);
	void mouseReleaseEvent(QMouseEvent* e);
	QPoint getPointCoords();

	int mode, dx, dy, adjustX, adjustY, modeBackup;
	bool windowChanged;
	QPoint currentPos;

};

#endif // IMAGEVIEW_H
